src/Controllers/TextosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using src.Models;

namespace src.Controllers
{
    [Authorize]
    public class TextosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TextosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Textos
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Texto.Include(t => t.Perfil);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Textos/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Texto == null)
            {
                return NotFound();
            }

            var texto = await _context.Texto
                .Include(t => t.Perfil)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (texto == null)
            {
                return NotFound();
            }

            return View(texto);
        }

        // GET: Textos/Create
        public IActionResult Create()
        {
            ViewData["IdPerfil"] = new SelectList(_context.Perfil, "Id", "NomePerfil");
            return View();
        }

        // POST: Textos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Data,Tipo,Artigo")] Texto texto)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var profile = await _context.Perfil.FirstOrDefaultAsync(m => m.IdUsuario == userId);
            var text = texto;
            text.IdPerfil = profile.Id;

            if (ModelState.IsValid)
            {
                _context.Add(texto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPerfil"] = new SelectList(_context.Perfil, "Id", "NomePerfil", texto.IdPerfil);
            return View(texto);
        }

        // GET: Textos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Texto == null)
            {
                return NotFound();
            }

            var texto = await _context.Texto.FindAsync(id);
            if (texto == null)
            {
                return NotFound();
            }
            ViewData["IdPerfil"] = new SelectList(_context.Perfil, "Id", "NomePerfil", texto.IdPerfil);
            return View(texto);
        }

        // POST: Textos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Data,Tipo,Artigo,IdPerfil")] Texto texto)
        {
            if (id != texto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(texto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TextoExists(texto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPerfil"] = new SelectList(_context.Perfil, "Id", "NomePerfil", texto.IdPerfil);
            return View(texto);
        }

        // GET: Textos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Texto == null)
            {
                return NotFound();
            }

            var texto = await _context.Texto
                .Include(t => t.Perfil)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (texto == null)
            {
                return NotFound();
            }

            return View(texto);
        }

        // POST: Textos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Texto == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Texto'  is null.");
            }
            var texto = await _context.Texto.FindAsync(id);
            if (texto != null)
            {
                _context.Texto.Remove(texto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TextoExists(int id)
        {
          return _context.Texto.Any(e => e.Id == id);
        }
    }
}

src/Views/Shared/_AvaliacoesFormPartial.cshtml
@model src.Models.Avaliacao

<div class="row p-lg-5">
    <div class="w-100">
        <h3>Sobre o texto, como voce avalia o entendimento ?</h3>
        <hr/>
        <form asp-action="Create" class="mt-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Entendimento" class="control-label"></label>
                <select asp-for="Entendimento" class="form-control" asp-items="Html.GetEnumSelectList<Entendimento>()"></select>
                <span asp-validation-for="Entendimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <textarea asp-for="Comentario" class="form-control" style="height: 100px"></textarea>
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="IdTexto" value="" id="id_texto" />
            <div class="form-group mt-5">
                <input type="submit" value="Concluir avaliação" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

    <script>
        const [,id] = document.location.href.split('Details');

        const inputIdTexto = document.getElementById("id_texto")

        inputIdTexto.value = id.replace('/','');
    </script>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary navbar-light box-shadow">
            <div class="container justify-content-between">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                     <img src="/images/logo.png" alt="Logo do projeto Letra Independente" />
                </a>
                    <ul class="navbar-nav">
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Textos" asp-action="Index">Artigos</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Textos" asp-action="Create">Publicar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Avaliacoes" asp-action="Index">Avaliacoes</a>
                            </li>
                            <li class="nav-item text-white">
                                <span class="nav-link text-white font-weight-bold">Olá @User.Identity.Name ! </span>
                            </li>
                            <li class="nav-item text-white">
                                <a class="nav-link text-white" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item text-white">
                                <a class="nav-link text-white" asp-area="" asp-controller="Usuarios" asp-action="Login">Login / Cadastro</a>
                            </li>
                        }
                    </ul>
            </div>
        </nav>
    </header>
    <main role="main" class="vh-100">
          @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>